version: '3'
services:
  admin_dashboard_esim:
    image: bijontalukder/admin_dashboard_esim:latest
    container_name: admin_dashboard_esim
    restart: always
    ports:
      - "3000:3000"
    network_mode: "host"
    environment:
      - NODE_ENV=production
    
      # - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # - DATABASE_URL=${DATABASE_URL}  # যদি ডাটাবেস ব্যবহার করেন
      # - SECRET_KEY=${SECRET_KEY} 
